"""add chunk_edges table

Revision ID: 10ca5ff04f67
Revises: 002
Create Date: 2026-03-28 11:09:20.760332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ca5ff04f67'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_doc_id', sa.String(length=12), nullable=False),
    sa.Column('source_chunk_index', sa.Integer(), nullable=False),
    sa.Column('target_doc_id', sa.String(length=12), nullable=False),
    sa.Column('target_chunk_index', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunk_edges', schema=None) as batch_op:
        batch_op.create_index('ix_edges_relation', ['relation'], unique=False)
        batch_op.create_index('ix_edges_source', ['source_doc_id', 'source_chunk_index'], unique=False)
        batch_op.create_index('ix_edges_target', ['target_doc_id', 'target_chunk_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunk_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_edges_target')
        batch_op.drop_index('ix_edges_source')
        batch_op.drop_index('ix_edges_relation')

    op.drop_table('chunk_edges')
    # ### end Alembic commands ###
