"""add scope to chat_sessions

Revision ID: dc0e861505bf
Revises: 343ff6823557
Create Date: 2026-04-07 17:16:11.979333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc0e861505bf'
down_revision: Union[str, Sequence[str], None] = '343ff6823557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('chat_sessions', sa.Column('scope_type', sa.String(length=20), nullable=True))
    op.add_column('chat_sessions', sa.Column('scope_value', sa.String(length=200), nullable=True))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'last_access',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_dc_collection'), table_name='document_collections')
    op.create_index(op.f('ix_document_collections_collection'), 'document_collections', ['collection'], unique=False)
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_document_collections_collection'), table_name='document_collections')
    op.create_index(op.f('ix_dc_collection'), 'document_collections', ['collection'], unique=False)
    op.alter_column('chat_sessions', 'last_access',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('chat_sessions', 'scope_value')
    op.drop_column('chat_sessions', 'scope_type')
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
